name: Docker Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create logs directory
        run: mkdir -p logs

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run container and generate logs
        run: docker run -v "$(pwd)/logs:/home/logs" logger

      - name: Check if log file exists
        run: |
          if [ ! -f logs/log.txt ]; then
            echo "Log file was not created"
            exit 1
          fi

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
          retention-days: 5
